name: ghpages

on: workflow_dispatch

jobs:
  update-gh-pages-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: dependencies
        run: npm install
      - name: angular
        run: npm install -g @angular/cli angular-cli-ghpages
      - name: build
        run: ng build --base-href "/AngularExo1/"
      - name: push-branch
        run: npx angular-cli-ghpages --dir=dist/exo1/browser
