# name: Build

# on:
#   push:
#     branches: [main]
#   workflow_dispatch:

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-node@v4
#         with:
#           node-version: 20

#       - name: Prepare
#         run: |
#           ls -l
#           npm install
#           npm run build
#           cd dist
#           npm link
#           cd ..
#           cd ..
#           ls -l
#           npm install -g @angular/cli
#           ng new AngularExoPage --defaults
#           cd AngularExoPage
#           npm link angular-cli-ghpages
#           ng add angular-cli-ghpages
#         # run: |
#         #   npm install
#         #   npm run build
#         #   npm install -g @angular/cli
#         #   ng add angular-cli-ghpages

#       - name: Deploy
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         run: |
#           ls -l
#           cd ..
#           ls -l
#           cd AngularExoPage
#           ng deploy --repo=git@github.com:Mysthaqua/AngularExo1.git --name=Mysthaqua --email=mysthaqua@gmail.com --base-href=/AngularExo1/ --dir=dist/exo1/browser

name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: angular process
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.4.0
        with:
          github_access_token: ${{ secrets.GH_TOKEN }} #Token que j'ai genéré et mis dans mes secret de repo
          build_configuration: production # dans angular.json c'est la valeur par default c'est peut-être pas la même pour tous
          base_href: /ExoAngular1/ # le nom de mon repo
          angular_dist_build_folder: dist/exo1/browser # dist/[nom_du_projet]/browser

permissions:
  contents: write # Au moment de faire le token il faut penser à lui autoriser l'ecriture des commit et du deployment
